### model
model_name_or_path: mistralai/Mistral-7B-v0.3

### method
stage: pt
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: beir--scifact--train--queries_only
cutoff_len: 512
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: pretrained--beir--scifact--train-queries_only
logging_steps: 2
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.05
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
