cutoff_len: 2048
dataset: beir--scifact--test--default
ddp_timeout: 180000000
do_train: true
eval_steps: 500
evaluation_strategy: steps
finetuning_type: lora
fp16: true
gradient_accumulation_steps: 16
learning_rate: 5.0e-05
logging_steps: 10
lora_alpha: 16
lora_rank: 8
lora_target: q_proj,v_proj,o_proj,k_proj
lr_scheduler_type: cosine
max_samples: 999999
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
num_train_epochs: 8.0
output_dir: query_generator_beir--scifact--test--default
overwrite_cache: true
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
save_steps: 500
stage: sft
template: llama3
val_size: 0.1
warmup_steps: 0.1
